[package]
name = "valence_anvil"
description = "A library for Minecraft's Anvil world format."
documentation.workspace = true
repository = "https://github.com/valence-rs/valence/tree/main/crates/valence_anvil"
readme = "README.md"
license.workspace = true
keywords = ["anvil", "minecraft", "deserialization"]
version.workspace = true
edition.workspace = true

[features]
default = ["valence"]

[dependencies]
byteorder.workspace = true
flate2.workspace = true
num-integer.workspace = true
thiserror.workspace = true
valence = { workspace = true, optional = true }
valence_nbt.workspace = true

[dev-dependencies]
anyhow.workspace = true
bevy_ecs.workspace = true
clap.workspace = true
criterion.workspace = true
flume.workspace = true
fs_extra.workspace = true
tempfile.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
zip.workspace = true

[dev-dependencies.reqwest]
workspace = true
default-features = false
# Avoid OpenSSL dependency on Linux.
features = ["rustls-tls", "blocking", "stream"]

[[bench]]
name = "world_parsing"
harness = false
