[package]
name = "valence_network"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
async-trait = "0.1.60"
base64 = "0.21.0"
bevy_app = "0.10.1"
bevy_ecs = "0.10.1"
bytes = "1.4.0"
flume = "0.10.14"
hmac = "0.12.1"
num-bigint = "0.4.3"
rand = "0.8.5"
rsa = "0.7.2"
rsa-der = "0.3.0"
serde = "1.0.160"
serde_json = "1.0.95"
sha1 = "0.10.5"
sha2 = "0.10.6"
thiserror = "1.0.40"
tokio = { version = "1.25.0", features = ["full"] }
tracing = "0.1.37"
uuid = "1.1.2"
valence = { path = "../valence", version = "0.2.0" }
valence_protocol = { path = "../valence_protocol", version = "0.1.0" }


[dependencies.reqwest]
version = "0.11.12"
default-features = false
# Avoid OpenSSL dependency on Linux.
features = ["rustls-tls", "json"]
