[package]
name = "valence_entity"
version.workspace = true
edition.workspace = true

[dependencies]
valence_core.workspace = true

[build-dependencies]
anyhow.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
serde_json.workspace = true
heck.workspace = true
serde.workspace = true
valence_macro_utils.workspace = true
